const AUTHOR_LOGO_MAP: Record<string, string> = {
  "29cm": "/logos/29cm.ico",
  "29씨엠": "/logos/29cm.ico",
  "8percent": "/logos/8percent.ico",
  "에잇퍼센트": "/logos/8percent.ico",
  "ab180": "/logos/ab180.ico",
  "토스": "/logos/toss.ico",
  "toss": "/logos/toss.ico",
  "당근": "/logos/daangn.ico",
  "당근마켓": "/logos/daangn.ico",
  "daangn": "/logos/daangn.ico",
  "카카오": "/logos/kakao.ico",
  "kakao": "/logos/kakao.ico",
  "카카오페이": "/logos/kakaopay.ico",
  "kakaopay": "/logos/kakaopay.ico",
  "무신사": "/logos/musinsa.ico",
  "musinsa": "/logos/musinsa.ico",
  "올리브영": "/logos/oliveyoung.ico",
  "oliveyoung": "/logos/oliveyoung.ico",
  "우아한형제들": "/logos/woowahan.ico",
  "우아한형제": "/logos/woowahan.ico",
  "woowahan": "/logos/woowahan.ico",
  "배달의민족": "/logos/woowahan.ico",
  "네이버": "/logos/naver.ico",
  "naver": "/logos/naver.ico",
  "라인": "/logos/line.ico",
  "line": "/logos/line.ico",
  "lycorp": "/logos/line.ico",
  "마켓컬리": "/logos/kurly.ico",
  "컬리": "/logos/kurly.ico",
  "kurly": "/logos/kurly.ico",
  "쏘카": "/logos/socar.ico",
  "socar": "/logos/socar.ico",
  "하이퍼커넥트": "/logos/hyperconnect.ico",
  "hyperconnect": "/logos/hyperconnect.ico",
  "데브시스터즈": "/logos/devsisters.ico",
  "devsisters": "/logos/devsisters.ico",
  "뱅크샐러드": "/logos/banksalad.ico",
  "banksalad": "/logos/banksalad.ico",
  "왓챠": "/logos/watcha.ico",
  "watcha": "/logos/watcha.ico",
  "다나와": "/logos/danawa.ico",
  "danawa": "/logos/danawa.ico",
  "레브잇": "/logos/levit.ico",
  "levit": "/logos/levit.ico",
  "올웨이즈": "/logos/levit.ico",
  "요기요": "/logos/yogiyo.ico",
  "yogiyo": "/logos/yogiyo.ico",
  "쿠팡": "/logos/coupang.ico",
  "coupang": "/logos/coupang.ico",
  "원티드": "/logos/wanted.ico",
  "wanted": "/logos/wanted.ico",
  "데이블": "/logos/dable.ico",
  "dable": "/logos/dable.ico",
  "사람인": "/logos/saramin.ico",
  "saramin": "/logos/saramin.ico",
  "직방": "/logos/zigbang.ico",
  "zigbang": "/logos/zigbang.ico",
  "콴다": "/logos/qanda.ico",
  "qanda": "/logos/qanda.ico",
  "mathpresso": "/logos/qanda.ico",
  "여기어때": "/logos/gccompany.ico",
  "gccompany": "/logos/gccompany.ico",
};

function normalizeAuthor(author: string): string {
  return author.toLowerCase().replace(/\s+/g, "").replace(/[().,_-]/g, "");
}

export const getLogoUrl = (author: string): string | null => {
  return AUTHOR_LOGO_MAP[normalizeAuthor(author)] ?? null;
};
