const TECH_LOGO_BASE_PATH = "/images/interview/tech-logos";

export interface TechLogoMeta {
  src: string;
  label: string;
}

const TECH_LOGO_BY_KEY: Record<string, TechLogoMeta> = {
  airflow: { src: `${TECH_LOGO_BASE_PATH}/airflow.svg`, label: "Airflow" },
  android: { src: `${TECH_LOGO_BASE_PATH}/android.svg`, label: "Android" },
  apacheairflow: { src: `${TECH_LOGO_BASE_PATH}/airflow.svg`, label: "Airflow" },
  apachekafka: { src: `${TECH_LOGO_BASE_PATH}/kafka.svg`, label: "Kafka" },
  apachespark: { src: `${TECH_LOGO_BASE_PATH}/spark.svg`, label: "Spark" },
  aws: { src: `${TECH_LOGO_BASE_PATH}/aws.svg`, label: "AWS" },
  awsiam: { src: `${TECH_LOGO_BASE_PATH}/aws.svg`, label: "AWS IAM" },
  backstage: { src: `${TECH_LOGO_BASE_PATH}/backstage.svg`, label: "Backstage" },
  bigquery: { src: `${TECH_LOGO_BASE_PATH}/bigquery.svg`, label: "BigQuery" },
  burpsuite: { src: `${TECH_LOGO_BASE_PATH}/burp-suite.svg`, label: "Burp Suite" },
  canvas: { src: `${TECH_LOGO_BASE_PATH}/html5.svg`, label: "Canvas" },
  chart: { src: `${TECH_LOGO_BASE_PATH}/chartjs.svg`, label: "Chart.js" },
  chartjs: { src: `${TECH_LOGO_BASE_PATH}/chartjs.svg`, label: "Chart.js" },
  cicd: { src: `${TECH_LOGO_BASE_PATH}/github-actions.svg`, label: "CI/CD" },
  cloud: { src: `${TECH_LOGO_BASE_PATH}/cloud.svg`, label: "Cloud" },
  cloudwatch: { src: `${TECH_LOGO_BASE_PATH}/aws.svg`, label: "CloudWatch" },
  css: { src: `${TECH_LOGO_BASE_PATH}/css.svg`, label: "CSS" },
  css3: { src: `${TECH_LOGO_BASE_PATH}/css.svg`, label: "CSS" },
  cypress: { src: `${TECH_LOGO_BASE_PATH}/cypress.svg`, label: "Cypress" },
  dart: { src: `${TECH_LOGO_BASE_PATH}/dart.svg`, label: "Dart" },
  dask: { src: `${TECH_LOGO_BASE_PATH}/python.svg`, label: "Python" },
  dast: { src: `${TECH_LOGO_BASE_PATH}/owasp.svg`, label: "DAST" },
  docker: { src: `${TECH_LOGO_BASE_PATH}/docker.svg`, label: "Docker" },
  eks: { src: `${TECH_LOGO_BASE_PATH}/kubernetes.svg`, label: "EKS" },
  elastic: { src: `${TECH_LOGO_BASE_PATH}/elastic.svg`, label: "Elastic" },
  edr: { src: `${TECH_LOGO_BASE_PATH}/elastic.svg`, label: "EDR" },
  fastapi: { src: `${TECH_LOGO_BASE_PATH}/fastapi.svg`, label: "FastAPI" },
  fastlane: { src: `${TECH_LOGO_BASE_PATH}/fastlane.svg`, label: "Fastlane" },
  figma: { src: `${TECH_LOGO_BASE_PATH}/figma.svg`, label: "Figma" },
  firebase: { src: `${TECH_LOGO_BASE_PATH}/firebase.svg`, label: "Firebase" },
  flutter: { src: `${TECH_LOGO_BASE_PATH}/flutter.svg`, label: "Flutter" },
  framer: { src: `${TECH_LOGO_BASE_PATH}/motion.svg`, label: "Motion" },
  framermotion: { src: `${TECH_LOGO_BASE_PATH}/motion.svg`, label: "Motion" },
  githubactions: { src: `${TECH_LOGO_BASE_PATH}/github-actions.svg`, label: "GitHub Actions" },
  go: { src: `${TECH_LOGO_BASE_PATH}/go.svg`, label: "Go" },
  golang: { src: `${TECH_LOGO_BASE_PATH}/go.svg`, label: "Go" },
  googlebigquery: { src: `${TECH_LOGO_BASE_PATH}/bigquery.svg`, label: "BigQuery" },
  gradle: { src: `${TECH_LOGO_BASE_PATH}/gradle.svg`, label: "Gradle" },
  grafana: { src: `${TECH_LOGO_BASE_PATH}/grafana.svg`, label: "Grafana" },
  iam: { src: `${TECH_LOGO_BASE_PATH}/aws.svg`, label: "IAM" },
  ios: { src: `${TECH_LOGO_BASE_PATH}/ios.svg`, label: "iOS" },
  java: { src: `${TECH_LOGO_BASE_PATH}/java.svg`, label: "Java" },
  jest: { src: `${TECH_LOGO_BASE_PATH}/jest.svg`, label: "Jest" },
  jetpack: { src: `${TECH_LOGO_BASE_PATH}/jetpack.svg`, label: "Jetpack" },
  jira: { src: `${TECH_LOGO_BASE_PATH}/jira.svg`, label: "Jira" },
  kafka: { src: `${TECH_LOGO_BASE_PATH}/kafka.svg`, label: "Kafka" },
  kms: { src: `${TECH_LOGO_BASE_PATH}/aws.svg`, label: "KMS" },
  kotlin: { src: `${TECH_LOGO_BASE_PATH}/kotlin.svg`, label: "Kotlin" },
  kubernetes: { src: `${TECH_LOGO_BASE_PATH}/kubernetes.svg`, label: "Kubernetes" },
  k8s: { src: `${TECH_LOGO_BASE_PATH}/kubernetes.svg`, label: "Kubernetes" },
  linux: { src: `${TECH_LOGO_BASE_PATH}/linux.svg`, label: "Linux" },
  looker: { src: `${TECH_LOGO_BASE_PATH}/looker.svg`, label: "Looker" },
  mlflow: { src: `${TECH_LOGO_BASE_PATH}/mlflow.svg`, label: "MLflow" },
  motion: { src: `${TECH_LOGO_BASE_PATH}/motion.svg`, label: "Motion" },
  mysql: { src: `${TECH_LOGO_BASE_PATH}/mysql.svg`, label: "MySQL" },
  network: { src: `${TECH_LOGO_BASE_PATH}/cloud.svg`, label: "Network" },
  next: { src: `${TECH_LOGO_BASE_PATH}/nextjs.svg`, label: "Next.js" },
  nextjs: { src: `${TECH_LOGO_BASE_PATH}/nextjs.svg`, label: "Next.js" },
  node: { src: `${TECH_LOGO_BASE_PATH}/nodejs.svg`, label: "Node.js" },
  nodejs: { src: `${TECH_LOGO_BASE_PATH}/nodejs.svg`, label: "Node.js" },
  observability: { src: `${TECH_LOGO_BASE_PATH}/grafana.svg`, label: "Observability" },
  openjdk: { src: `${TECH_LOGO_BASE_PATH}/java.svg`, label: "Java" },
  owasp: { src: `${TECH_LOGO_BASE_PATH}/owasp.svg`, label: "OWASP" },
  playwright: { src: `${TECH_LOGO_BASE_PATH}/playwright.svg`, label: "Playwright" },
  postgresql: { src: `${TECH_LOGO_BASE_PATH}/postgresql.svg`, label: "PostgreSQL" },
  postgres: { src: `${TECH_LOGO_BASE_PATH}/postgresql.svg`, label: "PostgreSQL" },
  postman: { src: `${TECH_LOGO_BASE_PATH}/postman.svg`, label: "Postman" },
  prometheus: { src: `${TECH_LOGO_BASE_PATH}/prometheus.svg`, label: "Prometheus" },
  python: { src: `${TECH_LOGO_BASE_PATH}/python.svg`, label: "Python" },
  pytorch: { src: `${TECH_LOGO_BASE_PATH}/pytorch.svg`, label: "PyTorch" },
  pytest: { src: `${TECH_LOGO_BASE_PATH}/pytest.svg`, label: "Pytest" },
  react: { src: `${TECH_LOGO_BASE_PATH}/react.svg`, label: "React" },
  reactnative: { src: `${TECH_LOGO_BASE_PATH}/react.svg`, label: "React Native" },
  reactquery: { src: `${TECH_LOGO_BASE_PATH}/tanstack.svg`, label: "TanStack Query" },
  redis: { src: `${TECH_LOGO_BASE_PATH}/redis.svg`, label: "Redis" },
  room: { src: `${TECH_LOGO_BASE_PATH}/android.svg`, label: "Room" },
  sast: { src: `${TECH_LOGO_BASE_PATH}/owasp.svg`, label: "SAST" },
  selenium: { src: `${TECH_LOGO_BASE_PATH}/selenium.svg`, label: "Selenium" },
  siem: { src: `${TECH_LOGO_BASE_PATH}/elastic.svg`, label: "SIEM" },
  spark: { src: `${TECH_LOGO_BASE_PATH}/spark.svg`, label: "Spark" },
  spring: { src: `${TECH_LOGO_BASE_PATH}/spring.svg`, label: "Spring" },
  springboot: { src: `${TECH_LOGO_BASE_PATH}/spring-boot.svg`, label: "Spring Boot" },
  sql: { src: `${TECH_LOGO_BASE_PATH}/sql.svg`, label: "SQL" },
  storybook: { src: `${TECH_LOGO_BASE_PATH}/storybook.svg`, label: "Storybook" },
  swift: { src: `${TECH_LOGO_BASE_PATH}/swift.svg`, label: "Swift" },
  swiftui: { src: `${TECH_LOGO_BASE_PATH}/swift.svg`, label: "SwiftUI" },
  table: { src: `${TECH_LOGO_BASE_PATH}/chartjs.svg`, label: "Table" },
  tanstack: { src: `${TECH_LOGO_BASE_PATH}/tanstack.svg`, label: "TanStack" },
  tanstackquery: { src: `${TECH_LOGO_BASE_PATH}/tanstack.svg`, label: "TanStack Query" },
  tensorflow: { src: `${TECH_LOGO_BASE_PATH}/tensorflow.svg`, label: "TensorFlow" },
  terraform: { src: `${TECH_LOGO_BASE_PATH}/terraform.svg`, label: "Terraform" },
  threatintelligence: { src: `${TECH_LOGO_BASE_PATH}/owasp.svg`, label: "Threat Intelligence" },
  ts: { src: `${TECH_LOGO_BASE_PATH}/typescript.svg`, label: "TypeScript" },
  typescript: { src: `${TECH_LOGO_BASE_PATH}/typescript.svg`, label: "TypeScript" },
  uikit: { src: `${TECH_LOGO_BASE_PATH}/ios.svg`, label: "UIKit" },
  vector: { src: `${TECH_LOGO_BASE_PATH}/elastic.svg`, label: "Vector DB" },
  vectordb: { src: `${TECH_LOGO_BASE_PATH}/elastic.svg`, label: "Vector DB" },
  vite: { src: `${TECH_LOGO_BASE_PATH}/vite.svg`, label: "Vite" },
  vpc: { src: `${TECH_LOGO_BASE_PATH}/aws.svg`, label: "VPC" },
  waf: { src: `${TECH_LOGO_BASE_PATH}/cloudflare.svg`, label: "WAF" },
};

function normalizeTechKey(label: string) {
  return label
    .trim()
    .toLowerCase()
    .replace(/\+/g, "plus")
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]/g, "");
}

export function getTechLogo(label: string): TechLogoMeta | null {
  return TECH_LOGO_BY_KEY[normalizeTechKey(label)] ?? null;
}
