services:
  - type: web
    name: dibut-workspace-server
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 4000
      - key: DATABASE_URL
        sync: false
      - key: BFF_URL
        sync: false
      - key: INTERNAL_API_SECRET
        sync: false
